-d C:\Users\pasca\OneDrive\Schule_BFH\5_Semester\TinyTapeoutProjekt\git\tt09-scope-bfh-mht1_3\fpga\gowin_vhdl_tang25k\impl\gwsynthesis\tt_project_env.vg
-p GW5A-25A-MBGA121N-1
-pn GW5A-LV25MG121NES
-cst C:\Users\pasca\OneDrive\Schule_BFH\5_Semester\TinyTapeoutProjekt\git\tt09-scope-bfh-mht1_3\fpga\gowin_vhdl_tang25k\src\tt_project_env.cst
-cfg C:\Users\pasca\OneDrive\Schule_BFH\5_Semester\TinyTapeoutProjekt\git\tt09-scope-bfh-mht1_3\fpga\gowin_vhdl_tang25k\impl\pnr\device.cfg
-sdc C:\Users\pasca\OneDrive\Schule_BFH\5_Semester\TinyTapeoutProjekt\git\tt09-scope-bfh-mht1_3\fpga\gowin_vhdl_tang25k\src\tt_project_env.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
-enable_dsrm 0
